name: app_manager
description: "Gerenciador de apps para windows."
publish_to: 'none'
version: 1.4.1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  process_run: ^1.2.2
  url_launcher: ^6.3.1
  window_manager: ^0.4.3
  shared_preferences: ^2.3.2

  flutter_svg: ^2.0.11
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
