name: app_manager
description: "Gerenciador de apps para windows."
publish_to: 'none'
version: 1.1.3

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.3
  url_launcher: ^6.2.6
  window_manager: ^0.3.9

  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
